### ISSUE TITLE
Auto Splitter Issues

### ISSUE THREAD

**Issue by DankDread** [Lemuura/It-Takes-Two-Autosplitter#2]
Hey guys, I have been playing It Takes Two and doing Inbounds runs using the autosplitter. I haven't used the autosplitter in a while, but after reactivating it it seems to not work no matter what I do. I can allow full access to the folder Livesplit is in, I did a clean install of Windows 11 Pro, and have tried multiple things from multiple forums. I am currently getting the following error code in the Event Viewer
"The handle is invalid

at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
at LiveSplit.ComponentUtil.DeepPointer.DerefString(Process process, ReadStringType type, StringBuilder sb)
at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
at LiveSplit.ASL.ASLState.RefreshValues(Process p)
at LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
at LiveSplit.UI.Components.ASLComponent.UpdateScript()"
I have tried using the newest version of Livesplit all the way down to 1.8.26 and I am stumped. I was previously getting an error for read / write to the memory, and it seems to not be happening anymore? I have fully disabled windows defender to make sure it isn't causing an issue and still no luck. Let me know if you need anymore information and I will gladly give it to you. 
I tried posting this on Livesplit's issues page but they turned me away and said to post it here

**Comment by Lemuura** [comment]
I'll take a look 👍There was a new game update recently so there being a problem makes sense haha

If you're in the ITT speedrunning discord feel free to post any issues with the autosplitter in the relevant channel there as well.

**Comment by Lemuura** [comment]
@DankDread Please check the discord when you're able to, we'll do all the troubleshooting and stuff there 😊
